name:
  tic-tac-toe

version:
  0.1.0.0

ghc-options:
  -Wall -Werror

dependencies:
  - base

library:
  source-dirs:
    - src/
  dependencies:
    - array
    - MissingH
    - mtl

executables:
  run-tic-tac-toe:
    main: Main.hs
    source-dirs:
      - app/
    dependencies:
      - tic-tac-toe
