name:
  tic-tac-toe

version:
  0.1.0.0

ghc-options:
  -Wall -Werror

dependencies:
  - base

library:
  source-dirs:
    - src/
  exposed-modules:
    - Lib
    - Split.LibSplit
  dependencies:
    - split

executables:
  run-tic-tac-toe:
    main: Main.hs
    source-dirs:
      - app/
    dependencies:
      - tic-tac-toe
  new-exec:
    main: NewExec.hs
    source-dirs:
      - app/
    dependencies:
      - tic-tac-toe

tests:
  tic-tac-toe-tests:
    main: Spec.hs
    source-dirs:
      - test/
    dependencies:
      - tic-tac-toe
  new-test:
    main: NewTest.hs
    source-dirs:
      - test/
    dependencies:
      - tasty-hunit
      - tic-tac-toe
